### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Giuca002** [prezmop/escapistscrypto#1]
This seems like a great tool but how do you use it. Can you write some documentation

**Comment by prezmop** [comment]
Hey, i have added some examples to the readme. Hopefully it's clear enough.

**Comment by Giuca002** [comment]
Hello, I have seen what have you done and its great, However I cant seem to be able to add my own items or even find the sprites of items.

**Comment by prezmop** [comment]
That's because the sprites are stored within the executable (or in Assets.dat on Mac/Linux). This tool can't touch that. If you want to extract the files, https://github.com/LAK132/SourceExplorer works. Sadly I don't know of a way to patch custom items. I have only managed to patch custom sprite textures to Assets.dat in the past, but that's as far as it goes.  No custom behavior or anything.
